package io.grpc.netty.shaded.io.netty.internal.tcnative;

import com.oracle.svm.core.annotate.AutomaticFeature;
import com.oracle.svm.core.jni.JNIRuntimeAccess;
import org.graalvm.nativeimage.hosted.Feature;

@AutomaticFeature
public class JniAccess implements Feature {
    public void beforeAnalysis(BeforeAnalysisAccess access) {
        try {
            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class);
            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslOpCipherServerPreference"));
            System.out.println("foofoo");
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslOpNoSSLv2"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslOpNoSSLv3"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslOpNoTLSv1"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslOpNoTLSv11"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslOpNoTLSv12"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslOpNoTLSv13"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslOpNoTicket"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslOpNoCompression"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSessCacheOff"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSessCacheServer"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslStConnect"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslStAccept"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslModeEnablePartialWrite"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslModeAcceptMovingWriteBuffer"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslModeReleaseBuffers"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSendShutdown"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslReceivedShutdown"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslErrorNone"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslErrorSSL"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslErrorWantRead"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslErrorWantWrite"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslErrorWantX509Lookup"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslErrorSyscall"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslErrorZeroReturn"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslErrorWantConnect"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslErrorWantAccept"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslMaxPlaintextLength"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslMaxRecordLength"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509CheckFlagAlwaysCheckSubject"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509CheckFlagDisableWildCards"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509CheckFlagNoPartialWildCards"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509CheckFlagMultiLabelWildCards"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vOK"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnspecified"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnableToGetIssuerCert"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnableToGetCrl"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnableToDecryptCertSignature"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnableToDecryptCrlSignature"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnableToDecodeIssuerPublicKey"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrCertSignatureFailure"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrCrlSignatureFailure"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrCertNotYetValid"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrCertHasExpired"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrCrlNotYetValid"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrCrlHasExpired"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrErrorInCertNotBeforeField"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrErrorInCertNotAfterField"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrErrorInCrlLastUpdateField"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrErrorInCrlNextUpdateField"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrOutOfMem"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrDepthZeroSelfSignedCert"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrSelfSignedCertInChain"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnableToGetIssuerCertLocally"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnableToVerifyLeafSignature"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrCertChainTooLong"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrCertRevoked"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrInvalidCa"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrPathLengthExceeded"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrInvalidPurpose"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrCertUntrusted"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrCertRejected"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrSubjectIssuerMismatch"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrAkidSkidMismatch"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrAkidIssuerSerialMismatch"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrKeyUsageNoCertSign"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnableToGetCrlIssuer"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnhandledCriticalExtension"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrKeyUsageNoCrlSign"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnhandledCriticalCrlExtension"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrInvalidNonCa"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrProxyPathLengthExceeded"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrKeyUsageNoDigitalSignature"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrProxyCertificatesNotAllowed"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrInvalidExtension"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrInvalidPolicyExtension"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrNoExplicitPolicy"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrDifferntCrlScope"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnsupportedExtensionFeature"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnnestedResource"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrPermittedViolation"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrExcludedViolation"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrSubtreeMinMax"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrApplicationVerification"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnsupportedConstraintType"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnsupportedConstraintSyntax"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrUnsupportedNameSyntax"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrCrlPathValidationError"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrPathLoop"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrSuiteBInvalidVersion"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrSuiteBInvalidAlgorithm"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrSuiteBInvalidCurve"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrSuiteBInvalidSignatureAlgorithm"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrSuiteBLosNotAllowed"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrSuiteBCannotSignP384WithP256"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrHostnameMismatch"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrEmailMismatch"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrIpAddressMismatch"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("x509vErrDaneNoMatch"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslErrorWantCertificateVerify"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslErrorWantPrivateKeyOperation"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSignRsaPkcsSha1"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSignRsaPkcsSha256"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSignRsaPkcsSha384"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSignRsaPkcsSha512"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSignEcdsaPkcsSha1"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSignEcdsaSecp256r1Sha256"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSignEcdsaSecp384r1Sha384"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSignEcdsaSecp521r1Sha512"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSignRsaPssRsaeSha256"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSignRsaPssRsaeSha384"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSignRsaPssRsaeSha512"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSignEd25519"));
//            JNIRuntimeAccess.register(NativeStaticallyReferencedJniMethods.class.getDeclaredMethod("sslSignRsaPkcs1Md5Sha1"));
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        }
    }
}
